<#
.SYNOPSIS
    Audit and remediate the mosaic-secure-mmwave repository.

.DESCRIPTION
    Fixes the issues that currently block the Implementation section:
      1. README claims a "physical ADC capture" that does not exist.
      2. Board variant is ODS throughout; the actual hardware is non-ODS.
      3. Provenance tags are prose, not machine-checkable.
      4. Directories for the three outstanding contributions do not exist.
      5. Optional: remove the C++ validator and transparency log.

    DEFAULT IS DRY-RUN. Nothing is modified unless you pass -Apply.

    Do NOT run this elevated. It touches git and your venv; running as
    admin creates root-owned files that break later non-elevated runs.
    Elevation is needed only for the DCA1000 NIC setup, which is a
    separate step and not performed here.

.PARAMETER RepoPath
    Path to the repository root. Defaults to the current directory.

.PARAMETER Apply
    Actually make the changes. Without this the script only reports.

.PARAMETER RemoveDeadWeight
    Also git-rm the C++ validator and transparency-log module. Separate
    switch because it is destructive; recoverable via git history.

.EXAMPLE
    .\mosaic_repo_fix.ps1 -RepoPath C:\dev\mosaic-secure-mmwave
    .\mosaic_repo_fix.ps1 -RepoPath C:\dev\mosaic-secure-mmwave -Apply
#>

[CmdletBinding()]
param(
    [string] $RepoPath = (Get-Location).Path,
    [switch] $Apply,
    [switch] $RemoveDeadWeight
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$script:Findings = New-Object System.Collections.Generic.List[object]
$script:Actions  = New-Object System.Collections.Generic.List[string]

function Add-Finding {
    param([string]$Severity, [string]$Item, [string]$Detail)
    $script:Findings.Add([pscustomobject]@{
        Severity = $Severity; Item = $Item; Detail = $Detail
    })
}

function Invoke-Change {
    param([string]$Description, [scriptblock]$Action)
    if ($Apply) {
        try {
            & $Action
            $script:Actions.Add("DONE    $Description")
        } catch {
            $script:Actions.Add("FAILED  $Description :: $($_.Exception.Message)")
        }
    } else {
        $script:Actions.Add("WOULD   $Description")
    }
}

# ----------------------------------------------------------------------
# 0. Preflight
# ----------------------------------------------------------------------
Write-Host "`n=== MOSAIC repository remediation ===" -ForegroundColor Cyan
Write-Host ("Mode: {0}" -f $(if ($Apply) { 'APPLY' } else { 'DRY-RUN (pass -Apply to change files)' })) `
    -ForegroundColor $(if ($Apply) { 'Yellow' } else { 'Green' })

$isAdmin = ([Security.Principal.WindowsPrincipal] `
    [Security.Principal.WindowsIdentity]::GetCurrent()
    ).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if ($isAdmin) {
    Write-Warning "You are running elevated. Prefer a NORMAL shell for git/python work."
}

if (-not (Test-Path (Join-Path $RepoPath '.git'))) {
    throw "No .git found at '$RepoPath'. Pass -RepoPath pointing at the repo root."
}
Set-Location $RepoPath
Write-Host "Repo: $RepoPath"

foreach ($tool in 'git', 'python') {
    if (-not (Get-Command $tool -ErrorAction SilentlyContinue)) {
        Add-Finding 'BLOCK' "$tool missing" "$tool is not on PATH."
    }
}

# ----------------------------------------------------------------------
# 1. Integrity: the "physical capture" claim
# ----------------------------------------------------------------------
Write-Host "`n--- 1. Integrity audit ---" -ForegroundColor Cyan

$readme = Join-Path $RepoPath 'README.md'
$badPhrases = @(
    'physical ADC capture',
    'physical IWR6843/DCA1000 reviewer dataset',
    'Physical IWR6843/DCA1000 reviewer dataset',
    'physical anchor path'
)

if (Test-Path $readme) {
    $readmeText = Get-Content $readme -Raw
    foreach ($p in $badPhrases) {
        if ($readmeText -like "*$p*") {
            Add-Finding 'CRITICAL' 'README overclaim' `
                "README contains '$p' but no physical capture exists (Phase E not done)."
        }
    }

    Invoke-Change "rewrite README provenance wording + prepend NOTICE" {
        $t = Get-Content $readme -Raw
        $t = $t -replace 'paired target/background physical ADC capture', `
                         'paired target/background EMULATED ADC test vector'
        $t = $t -replace 'Physical IWR6843/DCA1000 reviewer dataset', `
                         'Emulated IWR6843/DCA1000 test vector'
        $t = $t -replace 'physical IWR6843/DCA1000 reviewer dataset', `
                         'emulated IWR6843/DCA1000 test vector'

        $notice = @'
> **PROVENANCE NOTICE**
>
> Every dataset currently in this repository is **EMULATED**, generated by
> `scripts/generate_gen4_dataset.py` from a documented signal model. No
> physical radar capture has been performed yet. Emulated artifacts are
> software-validation fixtures and are **ineligible** for any performance,
> security, or deployment claim in the paper.
>
> Provenance for every artifact is declared in `PROVENANCE.md` and enforced
> by `scripts/check_provenance.py`.

'@
        if ($t -notlike '*PROVENANCE NOTICE*') { $t = $notice + $t }
        Set-Content -Path $readme -Value $t -Encoding UTF8 -NoNewline:$false
    }
} else {
    Add-Finding 'BLOCK' 'README.md missing' 'Cannot audit provenance wording.'
}

# ----------------------------------------------------------------------
# 2. Board variant: ODS -> non-ODS
# ----------------------------------------------------------------------
Write-Host "`n--- 2. Board variant audit ---" -ForegroundColor Cyan

$odsFiles = @(Get-ChildItem -Path $RepoPath -Recurse -File `
    -Include '*.yaml','*.yml','*.md','*.py','*.json' -ErrorAction SilentlyContinue |
    Where-Object { $_.FullName -notmatch '\\\.git\\' } |
    Where-Object { (Get-Content $_.FullName -Raw -ErrorAction SilentlyContinue) -match 'ods|ODS' })

if ($odsFiles.Count -gt 0) {
    Add-Finding 'HIGH' 'Wrong board variant' `
        ("{0} file(s) reference ODS; hardware is non-ODS (different antenna geometry)." -f $odsFiles.Count)
    foreach ($f in $odsFiles) { Write-Host ("    {0}" -f $f.FullName.Replace($RepoPath,'.')) }
}

$odsNamed = @(Get-ChildItem -Path $RepoPath -Recurse -File -ErrorAction SilentlyContinue |
    Where-Object { $_.Name -match 'ods' -and $_.FullName -notmatch '\\\.git\\' })
foreach ($f in $odsNamed) {
    $new = $f.Name -replace '_ods_', '_' -replace 'ods', 'isk'
    Invoke-Change ("git mv '{0}' -> '{1}'" -f $f.Name, $new) {
        & git mv --force -- $f.FullName (Join-Path $f.DirectoryName $new)
    }
}

# ----------------------------------------------------------------------
# 3. Machine-checkable provenance
# ----------------------------------------------------------------------
Write-Host "`n--- 3. Provenance enforcement ---" -ForegroundColor Cyan

Invoke-Change "create PROVENANCE.md" {
    $prov = @'
# Artifact provenance

Every dataset MUST appear here with exactly one tag.

| tag        | meaning                                              | paper-eligible |
|------------|------------------------------------------------------|----------------|
| `emulated` | synthesised from a documented signal model            | NO             |
| `measured` | captured from physical radar hardware                 | YES            |
| `derived`  | computed from a `measured` artifact                   | YES            |

Nothing tagged `emulated` may support a performance, security, or
deployment claim. `scripts/check_provenance.py` fails CI if an artifact
is untagged or if a figure/table cites an `emulated` artifact.

## Registry

| artifact | tag | sha256 | generator / session |
|----------|-----|--------|---------------------|
| data/emulated/gen4_target.bin | emulated | (fill) | generate_gen4_dataset.py |
| data/emulated/gen4_bg.bin     | emulated | (fill) | generate_gen4_dataset.py |
'@
    Set-Content -Path (Join-Path $RepoPath 'PROVENANCE.md') -Value $prov -Encoding UTF8
}

Invoke-Change "create scripts/check_provenance.py" {
    $checker = @'
#!/usr/bin/env python3
"""Fail if any dataset is untagged, or tagged `emulated` but cited as a result."""
import hashlib
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
REG = ROOT / "PROVENANCE.md"
VALID = {"emulated", "measured", "derived"}


def registry():
    if not REG.exists():
        sys.exit("PROVENANCE.md missing")
    out = {}
    for line in REG.read_text(encoding="utf-8").splitlines():
        cells = [c.strip() for c in line.split("|")[1:-1]]
        if len(cells) >= 3 and cells[1] in VALID:
            out[cells[0]] = {"tag": cells[1], "sha256": cells[2]}
    return out


def main() -> int:
    reg = registry()
    bad = []
    for p in list(ROOT.rglob("*.bin")) + list(ROOT.rglob("*.npy")):
        if ".git" in p.parts:
            continue
        rel = p.relative_to(ROOT).as_posix()
        if rel not in reg:
            bad.append(f"UNTAGGED  {rel}")
            continue
        want = reg[rel]["sha256"]
        if want and want != "(fill)":
            got = hashlib.sha256(p.read_bytes()).hexdigest()
            if got != want:
                bad.append(f"HASH MISMATCH  {rel}\n  want {want}\n  got  {got}")
    for line in bad:
        print(line)
    print(f"\n{len(reg)} registered, {len(bad)} problem(s)")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
'@
    $dir = Join-Path $RepoPath 'scripts'
    if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
    Set-Content -Path (Join-Path $dir 'check_provenance.py') -Value $checker -Encoding UTF8
}

# ----------------------------------------------------------------------
# 4. Directories for the three outstanding contributions
# ----------------------------------------------------------------------
Write-Host "`n--- 4. Contribution scaffolding ---" -ForegroundColor Cyan

$needed = [ordered]@{
    'configs/challenge'  = 'per-frame challenge codebooks (C2 / Phase F)'
    'sync'               = 'delta measurement and drift logs (C2 / Phase G)'
    'attack'             = 'A0 passive tag, A1 repeater (C1 / Phase H)'
    'data/emulated'      = 'emulated fixtures, never paper-eligible'
    'data/measured'      = 'physical captures, paper-eligible'
    'analysis'           = 'harness + generated tables'
}
foreach ($k in $needed.Keys) {
    $full = Join-Path $RepoPath $k
    if (-not (Test-Path $full)) {
        Add-Finding 'MEDIUM' "missing $k" $needed[$k]
        Invoke-Change "create $k/ (.gitkeep)" {
            New-Item -ItemType Directory -Path $full -Force | Out-Null
            Set-Content -Path (Join-Path $full '.gitkeep') -Value '' -Encoding UTF8
        }
    }
}

# ----------------------------------------------------------------------
# 5. Optional: remove dead weight
# ----------------------------------------------------------------------
if ($RemoveDeadWeight) {
    Write-Host "`n--- 5. Removing dead weight ---" -ForegroundColor Cyan
    foreach ($target in @('cpp')) {
        $full = Join-Path $RepoPath $target
        if (Test-Path $full) {
            Invoke-Change "git rm -r $target/ (recoverable from history)" {
                & git rm -r --quiet -- $full
            }
        }
    }
    $logs = @(Get-ChildItem -Path $RepoPath -Recurse -File -Filter '*transparency*' `
        -ErrorAction SilentlyContinue | Where-Object { $_.FullName -notmatch '\\\.git\\' })
    foreach ($f in $logs) {
        Invoke-Change ("git rm {0}" -f $f.Name) { & git rm --quiet -- $f.FullName }
    }
}

# ----------------------------------------------------------------------
# 6. Report
# ----------------------------------------------------------------------
Write-Host "`n=== FINDINGS ===" -ForegroundColor Cyan
if ($script:Findings.Count -eq 0) {
    Write-Host "  none" -ForegroundColor Green
} else {
    $script:Findings | Sort-Object Severity | Format-Table -AutoSize -Wrap
}

Write-Host "`n=== ACTIONS ===" -ForegroundColor Cyan
foreach ($a in $script:Actions) {
    $c = if ($a.StartsWith('FAILED')) { 'Red' }
         elseif ($a.StartsWith('DONE')) { 'Green' } else { 'Gray' }
    Write-Host "  $a" -ForegroundColor $c
}

if (-not $Apply) {
    Write-Host "`nDry run only. Re-run with -Apply to make these changes." -ForegroundColor Yellow
} else {
    Write-Host "`nReview with:  git status ; git diff" -ForegroundColor Yellow
    Write-Host "Then:         python scripts\check_provenance.py" -ForegroundColor Yellow
}

Write-Host "`nNOT handled here (do manually):" -ForegroundColor Cyan
Write-Host "  * make the repo PRIVATE, or mirror to anonymous.4open.science for review"
Write-Host "  * commit or delete the uncommitted Phase-D work (5 commits vs 12 phases)"
Write-Host "  * DCA1000 NIC setup -- needs an ELEVATED shell, separate step`n"
